#pragma once
//Config file keywords

#define CFG_KEYWORD_VIDEO						"#VIDEO"
#define CFG_KEYWORD_ENDL_VIDEO					"#ENDL_VIDEO"

#define CFG_KEYWORD_KEYBINDINGS					"#KEY_BINDINGS"
#define CFG_KEYWORD_ENDL_KEYBINDINGS			"#ENDL_KEY_BINDINGS"

#define CFG_KEYWORD_CONTROLOPTIONS				"#CONTROLOPTIONS"
#define CFG_KEYWORD_ENDL_CONTROLOPTIONS			"#ENDL_CONTROLOPTIONS"

#define CFG_PROPERTY_MOUSESENSITIVITY			"MouseSensitivity"
#define CFG_PROPERTY_MOVEMENTSTEP				"MovementStep"

#define CFG_KEYWORD_PHYSICS						"#PHYSICS"
#define CFG_KEYWORD_ENDL_PHYSICS				"#ENDL_PHYSICS"

#define CFG_KEYWORD_SOUND						"#SOUND"
#define CFG_KEYWORD_ENDL_SOUND					"#ENDL_SOUND"

#define CFG_KEYWORD_MESH						"#MESH"
#define CFG_KEYWORD_ENDL_MESH					"#ENDL_MESH"

#define CFG_KEYWORD_AI							"#AI"
#define CFG_KEYWORD_ENDL_AI						"#ENDL_AI"

#define CFG_KEYWORD_DATAPERSISTENCY				"#DATAPERSISTENCY"
#define CFG_KEYWORD_ENDL_DATAPERSISTENCY		"#ENDL_DATAPERSISTENCY"

#define CFG_KEYWORD_LUASCRIPTING				"#LUASCRIPTING"
#define CFG_KEYWORD_ENDL_LUASCRIPTING			"#ENDL_LUASCRIPTING"

#define CFG_PROPERTY_WINDOWHEIGHT				"WindowHeight"
#define CFG_PROPERTY_WINDOWWIDTH				"WindowWidth"

#define CFG_PROPERTY_ENGINE						"Engine"
#define CFG_PROPERTY_ISACTIVE					"IsActive"